sudo: false
language: python
python:
  - '3.6'
# command to install dependencies
install:
  - pip install --upgrade --pre tox
# # command to run tests
env:
  matrix:
    # coveralls is not listed in tox's envlist, but should run in travis
    - TOXENV=coveralls
    # note: please use "tox --listenvs" to populate the build matrix below
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36

matrix:
  include:
    - env: TOXENV=py27
      python: '2.7'
    - env: TOXENV=py34
      python: '3.3'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py36

script: tox --recreate

notifications:
  email:
    - efrain70@gmail.com
